from enum import Enum


class HandlePoolResponse(Enum):
    PASSED = "PASSED"
    IGNORABLE = "IGNORABLE"
    MIN_LIQUIDITY = "MIN_LIQUIDITY"
    MCAP_RANGE = "MCAP_RANGE"
    TOP_5_HOLDERS_ABOVE_TH = "TOP_5_HOLDERS_ABOVE_TH"
    LOW_HOLDER_COUNT = "LOW_HOLDER_COUNT"
    MIN_24H_VOLUME = "MIN_24H_VOLUME"
    NO_BUY_OUTLIER = "NO_BUY_OUTLIER"
    ERROR = "ERROR" 